### ISSUE TITLE
Legend of Silverpeak leaves graphics semi-permanently on MiSTer FPGA

### ISSUE THREAD

**Issue by wizdude** [MiSTer-devel/Atari7800_MiSTer#1]
I tested out the Atari 7800 core tonight and uploaded some ROM's. I was playing a variety of games, but after playing "Legend of Silverpeak" I reset back to the main mister screen (shift-control-alt-alt) while in the middle of the game. I could see the flashing image of the character from the game on the main MiSTer screen along with another flickering graphical glitch (two horizontal bars) at the bottom of the screen. I reset again - it was still there. I did a cold restart - still there. I then power cycled the MiSTer and while the character was gone, the other graphical glitch was still there.

While launching other cores (CPS2, Arcade, C64 etc) the graphical glitch was still visible. I couldn't get rid of it.

I managed to get rid of this by going back into the 7800 core and launching the "Legend of Silverpeak" game again. i waited until i got to the same section where I reset from before (you fight other creatures that you encounter) and waited until this completed and the graphical glitch was no longer. I went back to the main MiSTer screen and the glitch has gone.

I've gone back in twice and been able to reproduce this. My concern is not a glitch in a game, but that even when I powered off the MiSTer and powered it back on again that the glitch was still visible.

I have no idea how or why this occurs. The issue appears to be only with this one specific 7800 ROM. I haven't encountered the problem with any other titles.

**Comment by Kitrinx** [comment]
this seems like some leftover data in the framebuffer that was just continuing to get drawn for some reason. It's probably not something specific to this core but rather the way that the mister framework functions. I don't think I can do anything to help you with this on my end.

**Comment by Kitrinx** [comment]
There is nothing actionable here, as this is an issue with the scaler and the framework maintaining a buffer in DDR3 memory. It's nothing I can address as part of the core. If you feel this is an issue specific to this core I will need more details into how you feel the original hardware is misbehaving.
