### ISSUE TITLE
Paddle control with mouse is too slow, not like original

### ISSUE THREAD

**Issue by rsn8887** [MiSTer-devel/Atari7800_MiSTer#12]
In the old 2600 core, I could move my player both very fast and very slow in Ka-Boom with a mouse. In this core, it seems the paddle mouse control has a maximum (and minimum) speed, and a small dynamic range. Even the fastest mouse motion results in only a somewhat slow maximum player movement speed. In addition, it seems there's also a minimum speed: even if I move the mouse very very slowly, my player sprite moves still a bit fast.

On original Atari 2600 hardware, the paddle control was much more fine grained than the mouse control in this core: very slow motion resulted in extremely slow player motion, and very fast motion was also possible and almost instantaneous.

**Comment by Kitrinx** [comment]
This should now be resolved.
