### ISSUE TITLE
Pursuit of the Pink Panther prototype doesn't work

### ISSUE THREAD

**Issue by KremlingKuthroat19** [MiSTer-devel/Atari7800_MiSTer#15]
I've tested every Atari 2600 game and they all run perfectly, except Pursuit of the Pink Panther. I've gotten the garbled screen which you usually get when you run a game that is using the wrong selected mapper. I have set the mapper to auto, am using the latest Rom Hunter collection version, the game works in Stella and I've tried using all the different mapper types with no luck.

Is there a known issue as to why this game doesn't run?

**Comment by Kitrinx** [comment]
Make sure the rom size is 8kb (good dump) and not 9kb (bad dump). The good dump works fine.

**Comment by Kitrinx** [comment]
Was this issue resolved?

**Comment by birdybro** [comment]
The No-Intro dump appears to be a bad dump, despite being listed as a trusted dump.

https://datomatic.no-intro.org/index.php?page=show_record&s=88&n=0716

This matches the 9kb file I have in my collection. It also matches the one from an atari age thread awhile ago. Apparently, according to that thread, banks 2 and 3 are swapped in the bad dump. According to one of the dumpers:

> I think we got slices `#2` and `#3` swapped during dumping (current `#2` is executed in 0xc00..0xfff, `#3` in 0x800..0xbff).

**Comment by Kitrinx** [comment]
I know for certain the 9kb one is a bad dump, no matter where it happens to appear, and I don't plan to ever support the bad one. Stella does this by basically rewriting the file into the good dump, but I'm not really interested in contributing to the continued existence of the bad one. The good one does work perfectly however, even though the game itself is pretty mediocre.

**Comment by birdybro** [comment]
I was not suggesting that you support it, merely showing that even no-intro has a bad dump here, for @KremlingKuthroat19 's benefit when searching for it.

**Comment by mariomadproductions** [comment]
I've marked the ROM as bad in No-Intro. So this 8kb dump is a modification of the bad dump, to correct it? Or is it a redump? Either way, would you mind providing instructions on how to convert the bad dump into the good dump - then I can add it to No-Intro. Thanks.

**Comment by Kitrinx** [comment]
https://github.com/stella-emu/stella/blob/master/src/emucore/CartWD.cxx#L30-L36

That should explain it.

**Comment by mariomadproductions** [comment]
Could you post a sha256 of the proper ROM so I can confirm I've got the right one?

**Comment by Kitrinx** [comment]
SHA256 is 0029d4ff16a94ecdbf75d7e7de9c074f7ec2775d2c68902f84295a674b65f7da

I see nothing actionable here so I am going to close this issue. Feel free to reopen it if the correct dump of the ROM does not work.
