### ISSUE TITLE
Tower Toppler bug

### ISSUE THREAD

**Issue by dspiteri** [MiSTer-devel/Atari7800_MiSTer#8]
I noticed this game now ends a level immediately and moves to the next one, pretty sure it was working just a couple of weeks ago on Atari7800_20211128.rbf which hasn't updated. Weird.

**Comment by Kitrinx** [comment]
This is not a bug. You have changed the position of one of the difficulty switches. The game uses one of them as a "feature" to skip levels to the point where you want to be. Change them to the other position and this behavior will stop.

**Comment by dspiteri** [comment]
Ha so it is, thanks for following up!
